### ISSUE TITLE
BASALT is stuck in the middle

### ISSUE THREAD

**Issue by shashank-KU** [EMBL-PKU/BASALT#53]
Hi, 
I am running the BASALT, here is the last steps where BASALT stuck for couple of days-

```
mkdir: cannot create directory ‘coverage_filtration_matrix_10’: File exists
10 Coverage filtration done!
Parsing 1_SRR23604268.fa kmer file
Parsing 2_SRR23604271.fa kmer file
READing 1_SRR23604268.fa.kmer.txt
READing 2_SRR23604271.fa.kmer.txt
Bin_kmer exists
0 bins are waiting for TNFs filtration
mkdir: cannot create directory ‘TNF_filtration_matrix_10’: File exists
Writing retrieved bins
mkdir: cannot create directory ‘BestBinset_outlier_refined_filtrated_retrieved_retrieved_10’: File exists
Checking quality of retrieved bins
Iteration-10 accomplished. Left 0 iteration(s).
Rename BestBinset_outlier_refined_filtrated_retrieved_retrieved_3 to BestBinset_outlier_refined_filtrated_retrieved_retrieved
mv: cannot stat 'Bin_connecting_contigs*': No such file or directory
mv: cannot stat '*_selected_contigs.txt': No such file or directory
mv: cannot stat '*_elemimated_contig.txt': No such file or directory
mv: cannot stat '*_bin_extract_contig.txt': No such file or directory
Contig retrieve within group done
Starting OLC process
Processing with bins in BestBinset_outlier_refined_filtrated_retrieved_retrieved
Forming similar bins file
Multiple threads started
Processing 1_SRR23604268.fa_100_concoct_genomes.10.fa
Processing 2_SRR23604271.fa_0.9_maxbin2_genomes.1.fa
Utilization of 1_SRR23604268.fa_400_metabat_genomes.1.fa  to elongate 2_SRR23604271.fa_0.9_maxbin2_genomes.1.fa
Utilization of 2_SRR23604271.fa_200_concoct_genomes.12.fasta  to elongate 1_SRR23604268.fa_100_concoct_genomes.10.fa
Transfroming coverage matrix
Transfroming coverage matrix
[1.]
Finding outliner from 1_SRR23604268.fa_400_metabat_genomes.1.fa
15 outliers in 1_SRR23604268.fa_400_metabat_genomes.1.fa with threshold of 1
-------------------------
11 outliers in 1_SRR23604268.fa_400_metabat_genomes.1.fa with threshold of 1.5
-------------------------
6 outliers in 1_SRR23604268.fa_400_metabat_genomes.1.fa with threshold of 3
-------------------------
Calculating TNFs of 1_SRR23604268.fa_400_metabat_genomes.1.fa
Use of uninitialized value $kmerlengthprobe in concatenation (.) or string at /home/shashank/miniconda3/envs/BASALT/bin/calc.kmerfreq.pl line 133.
100 sequences 100 >= 500 bp

```

I am also attaching the log files that has been generated. There are somehow 2 logs files generated. Any suggestions?

[BASALT_log.txt](https://github.com/user-attachments/files/17071491/BASALT_log.txt)
[Basalt_log.txt](https://github.com/user-attachments/files/17071496/Basalt_log.txt)

**Comment by noddevil4949** [comment]
Hi,

We have addressed this issue in our latest version of BASALT. If you would like to continue BASALT, you can terminate the program and restart, BASALT will continue from your last step. Please update BASALT version once you have finished this run.

Cheers,
BASALT team

**Comment by camillaln** [comment]
Hi, 
I updated BASALT using conda. However, it is still hanging at the BestBin_outlier_test. 
It looks like basalt_env.yml has not been updated? I has - basalt=1.0.1=0 under dependencies.
Could you please update?
Thanks,
camilla
